version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - custom_network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adrian
      MYSQL_DATABASE: skills_2023
      MYSQL_USER: adrian
      MYSQL_PASSWORD: g]tHH[[iQC8oouw4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - custom_network

volumes:
  db_data:

networks:
  custom_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.227.0/24